# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vacation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vacation.proto',
  package='beevacay',
  serialized_pb=_b('\n\x0evacation.proto\x12\x08\x62\x65\x65vacay\"S\n\x0e\x42\x65\x65vacayConfig\x12/\n\x0evacation_entry\x18\x01 \x03(\x0b\x32\x17.beevacay.VacationEntry\x12\x10\n\x08username\x18\x02 \x01(\t\"W\n\rVacationEntry\x12\x11\n\tgoal_name\x18\x01 \x03(\t\x12\x33\n\x10vacation_pattern\x18\x02 \x03(\x0b\x32\x19.beevacay.VacationPattern\"\xbe\x02\n\x0fVacationPattern\x12\"\n\nstart_date\x18\x01 \x01(\x0b\x32\x0e.beevacay.Date\x12 \n\x08\x65nd_date\x18\x02 \x01(\x0b\x32\x0e.beevacay.Date\x12<\n\x11\x65xcluded_weekdays\x18\x03 \x03(\x0e\x32!.beevacay.VacationPattern.Weekday\x12\x14\n\tgoal_rate\x18\x04 \x01(\x05:\x01\x30\x12*\n\x1b\x64\x61ngerous_attempt_to_delete\x18\x05 \x01(\x08:\x05\x66\x61lse\"e\n\x07Weekday\x12\n\n\x06MONDAY\x10\x00\x12\x0b\n\x07TUESDAY\x10\x01\x12\r\n\tWEDNESDAY\x10\x02\x12\x0c\n\x08THURSDAY\x10\x03\x12\n\n\x06\x46RIDAY\x10\x04\x12\x0c\n\x08SATURDAY\x10\x05\x12\n\n\x06SUNDAY\x10\x06\"\"\n\x04\x44\x61te\x12\r\n\x05month\x18\x01 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_VACATIONPATTERN_WEEKDAY = _descriptor.EnumDescriptor(
  name='Weekday',
  full_name='beevacay.VacationPattern.Weekday',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MONDAY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TUESDAY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEDNESDAY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THURSDAY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRIDAY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SATURDAY', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUNDAY', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=420,
  serialized_end=521,
)
_sym_db.RegisterEnumDescriptor(_VACATIONPATTERN_WEEKDAY)


_BEEVACAYCONFIG = _descriptor.Descriptor(
  name='BeevacayConfig',
  full_name='beevacay.BeevacayConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vacation_entry', full_name='beevacay.BeevacayConfig.vacation_entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='beevacay.BeevacayConfig.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=111,
)


_VACATIONENTRY = _descriptor.Descriptor(
  name='VacationEntry',
  full_name='beevacay.VacationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_name', full_name='beevacay.VacationEntry.goal_name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vacation_pattern', full_name='beevacay.VacationEntry.vacation_pattern', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=200,
)


_VACATIONPATTERN = _descriptor.Descriptor(
  name='VacationPattern',
  full_name='beevacay.VacationPattern',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_date', full_name='beevacay.VacationPattern.start_date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='beevacay.VacationPattern.end_date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='excluded_weekdays', full_name='beevacay.VacationPattern.excluded_weekdays', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goal_rate', full_name='beevacay.VacationPattern.goal_rate', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dangerous_attempt_to_delete', full_name='beevacay.VacationPattern.dangerous_attempt_to_delete', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VACATIONPATTERN_WEEKDAY,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=521,
)


_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='beevacay.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='month', full_name='beevacay.Date.month', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='day', full_name='beevacay.Date.day', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=557,
)

_BEEVACAYCONFIG.fields_by_name['vacation_entry'].message_type = _VACATIONENTRY
_VACATIONENTRY.fields_by_name['vacation_pattern'].message_type = _VACATIONPATTERN
_VACATIONPATTERN.fields_by_name['start_date'].message_type = _DATE
_VACATIONPATTERN.fields_by_name['end_date'].message_type = _DATE
_VACATIONPATTERN.fields_by_name['excluded_weekdays'].enum_type = _VACATIONPATTERN_WEEKDAY
_VACATIONPATTERN_WEEKDAY.containing_type = _VACATIONPATTERN
DESCRIPTOR.message_types_by_name['BeevacayConfig'] = _BEEVACAYCONFIG
DESCRIPTOR.message_types_by_name['VacationEntry'] = _VACATIONENTRY
DESCRIPTOR.message_types_by_name['VacationPattern'] = _VACATIONPATTERN
DESCRIPTOR.message_types_by_name['Date'] = _DATE

BeevacayConfig = _reflection.GeneratedProtocolMessageType('BeevacayConfig', (_message.Message,), dict(
  DESCRIPTOR = _BEEVACAYCONFIG,
  __module__ = 'vacation_pb2'
  # @@protoc_insertion_point(class_scope:beevacay.BeevacayConfig)
  ))
_sym_db.RegisterMessage(BeevacayConfig)

VacationEntry = _reflection.GeneratedProtocolMessageType('VacationEntry', (_message.Message,), dict(
  DESCRIPTOR = _VACATIONENTRY,
  __module__ = 'vacation_pb2'
  # @@protoc_insertion_point(class_scope:beevacay.VacationEntry)
  ))
_sym_db.RegisterMessage(VacationEntry)

VacationPattern = _reflection.GeneratedProtocolMessageType('VacationPattern', (_message.Message,), dict(
  DESCRIPTOR = _VACATIONPATTERN,
  __module__ = 'vacation_pb2'
  # @@protoc_insertion_point(class_scope:beevacay.VacationPattern)
  ))
_sym_db.RegisterMessage(VacationPattern)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), dict(
  DESCRIPTOR = _DATE,
  __module__ = 'vacation_pb2'
  # @@protoc_insertion_point(class_scope:beevacay.Date)
  ))
_sym_db.RegisterMessage(Date)


# @@protoc_insertion_point(module_scope)
